export const allProperties = [
    {
        id: '5b230031-ccc9-4972-9d00-ef6010b81d84',
        details: {
            coordinates: [55.8687, -4.2517],
            rent: '928.53',
            driving: null,
            cycling: null,
            walking: null,
            train: null,
            bus: null,
            nearestTrainStation: [],
            nearestBusStop: [],
        },
    },
    {
        id: '923869bd-90a3-4979-95c1-83a7dfdbcd77',
        details: {
            coordinates: [55.87, -4.2546],
            rent: '851.91',
            driving: null,
            cycling: null,
            walking: null,
            train: null,
            bus: null,
            nearestTrainStation: [],
            nearestBusStop: [],
        },
    },
    {
        id: 'e2f03685-1acf-40fb-875f-72fefd8a5cc5',
        details: {
            coordinates: [55.8453, -4.2905],
            rent: '554.10',
            driving: null,
            cycling: null,
            walking: null,
            train: null,
            bus: null,
            nearestTrainStation: [],
            nearestBusStop: [],
        },
    },
    {
        id: '874f6b01-ffd1-47f3-89dd-aefad1b6ff4c',
        details: {
            coordinates: [55.8791, -4.2228],
            rent: '811.21',
            driving: null,
            cycling: null,
            walking: null,
            train: null,
            bus: null,
            nearestTrainStation: [],
            nearestBusStop: [],
        },
    },
    {
        id: '34ae6b26-6eef-4321-963b-a7175400ca08',
        details: {
            coordinates: [55.8513, -4.2236],
            rent: '652.02',
            driving: null,
            cycling: null,
            walking: null,
            train: null,
            bus: null,
            nearestTrainStation: [],
            nearestBusStop: [],
        },
    },
];
